#!/usr/bin/env python

import os
import shutil

crabline = "crab -create -submit -cfg "

def isCrabConfig(filename):

	if ".cfg" in filename:
		return True

	return False

def main():
	# for now, use os.getcwd()
	for path, dirs, files in os.walk(os.getcwd()):
		if path != os.getcwd():
			continue

		for file in files:
			# Check if the inside is set up like a crab file.
			if not isCrabConfig(os.path.join(path, file)):
				continue
			os.system(crabline + file)

if __name__ == '__main__':
	main()
