#!/usr/bin/env python

import optparse
import os
import shutil
import sys

from AutoCrab.AutoCrab import core

def main():
	parser = optparse.OptionParser()
	parser.add_option("-r", "--recursive", dest="recursive", action="store_true", help="The DBS to look up datasets in.")
	(opts, args) = parser.parse_args()

	for arg in args:
		if arg not in valid_commands.keys() and arg not in valid_functions.keys():
			print "Error: unrecognized autocrab command."
		else:
			doAutoCrab(arg, opts.recursive)

if __name__ == '__main__':
	main()
