#!/usr/bin/env python

import optparse
import os
import shutil
import sys

from AutoCrab.AutoCrab2 import core

def main():
	parser = optparse.OptionParser()
	parser.add_option("-r", "--recursive", dest="recursive", action="store_true", help="The DBS to look up datasets in.")
	(opts, args) = parser.parse_args()

	for arg in args:
		if not core.isValidCommand(arg):
			print "Error: unrecognized autocrab command."
		else:
			core.doAutoCrab(arg, opts.recursive)

if __name__ == '__main__':
	main()
